Feat: 커스텀 input 컴포넌트 생성
lulutraining/lulutraining pull request #27
Opened 2022-12-18 14:41 UTC by jiyun-par

[필수 props]
- label: input 상단 이름
- register: react-hook-form register
- placeholderTxt: placeholder 텍스트

[옵션 props]
- value: default value
- autoFocus: default 값 false
- types: default 값 text
- errorMsg: input validate 에러 메세지

2022-12-18 15:01 UTC, sso-hyeon approved these changes

2022-12-18 17:12 UTC, isabellaji reviewed
@jiyun-par 기존에 AuthInput과 기능이 일치한데 AuthInput을 수정하지 않고 CustomInput을 따로 만든 이유가 있을까요?

2022-12-19 00:39 UTC, jiyun-par commented
> @jiyun-par 기존에 AuthInput과 기능이 일치한데 AuthInput을 수정하지 않고 CustomInput을 따로 만든 이유가 있을까요?

기존의 AuthInput은 로그인&회원가입 두군데서 동일하게 사용해서 그대로 두고, 그 외 input들은 사용할때마다 커스텀하는게 좋을 것 같아서 따로 만들었습니다.

2022-12-19 00:53 UTC, isabellaji reviewed
@jiyun-par 어디에서 사용하는지에 따라 컴포넌트를 나눈다면, 동일한 기능을 하지만 이름만 다른 컴포넌트가 불필요하게 계속 생길 수 있을 것 같아요! AuthInput을 CustomInput으로 바꾸고 모두 CustomInput으로 사용하는건 어떠신가요?

2022-12-19 00:54 UTC, jiyun-par commented
> @jiyun-par 어디에서 사용하는지에 따라 컴포넌트를 나눈다면, 동일한 기능을 하지만 이름만 다른 컴포넌트가 불필요하게 계속 생길 수 있을 것 같아요! AuthInput을 CustomInput으로 바꾸고 모두 CustomInput으로 사용하는건 어떠신가요?

네네! 그렇게 수정하겠습니다

2022-12-19 02:12 UTC, isabellaji requested changes

2022-12-19 02:12 UTC, isabellaji commented on types/auth.ts
> +  nickname?: string;
nickname을 displayName으로 변경해주세요 firebase auth 보면 나와있어요!

2022-12-19 02:12 UTC, isabellaji commented on components/Form/CustomInput/index.tsx
> +export const emailValidation = {
변수는 컴포넌트 안으로 넣어주세욤!

2022-12-19 02:12 UTC, isabellaji commented on components/Form/CustomInput/index.tsx
> +  inputType?: string;
inputType, autoFocus, value 값이 무조건 넘겨받아야 하는 값이라면 '?' 제거 부탁드려용!

2022-12-19 02:12 UTC, isabellaji commented on components/Form/CustomInput/index.tsx
> +      {label === 'Password' ? (
type 부분의 조건문만 변경한다면 TextField에 있는 조건은 제거할 수 있을 것 같아용!

2022-12-19 02:12 UTC, isabellaji commented on components/Form/CustomInput/index.tsx
> +  inputType?: string;
@jiyun-par

2022-12-19 12:31 UTC, isabellaji requested changes

2022-12-19 12:31 UTC, isabellaji commented on types/auth.ts
> +export interface RegistInput {
RequestAuth는 firebase auth와 통신할때 사용하는 Interface인데 이름을 바꾼 이유가 있을까요? 그리고 firebase auth에 age, height, weight를 추가할 수 있나요?

2022-12-19 12:32 UTC, isabellaji commented on components/Form/CustomInput/index.tsx
> +      {label === 'Password' ? (
type={!passwordVisible ? 'password' : 'text'}
type={type}

2022-12-19 13:23 UTC, isabellaji approved these changes

2022-12-19 16:11 UTC, merged