Feature/oz 25 button
lulutraining/lulutraining pull request #31
Opened 2022-12-20 07:44 UTC by jiyun-par

- onClickNext: 다음 단계로 넘어가는 버튼 click 함수
 => form 내부에 있는 경우 handleSubmit 함수가 onClickNext 함수 대신에 작동 가능 하기 때문 에 옵션 설정
- onClickPrev: 이전 단계로 넘어가는 버튼 click 함수

2022-12-21 09:59 UTC, sso-hyeon approved these changes

2022-12-26 04:36 UTC, isabellaji requested changes

2022-12-26 04:36 UTC, isabellaji commented on components/Button/PrevNextButton/index.tsx
> +      <button type="button" onClick={onClickPrev} className="button-prev">
html button 바로 사용하지 않고 mui button 사용하면 default button 스타일을 지우는 과정을 거치지 않을 수 있어요!
https://mui.com/material-ui/react-button/

2022-12-26 05:58 UTC, isabellaji approved these changes

2022-12-26 06:01 UTC, merged