Feat: 회원가입 페이지 UI
lulutraining/lulutraining pull request #34
Opened 2022-12-23 17:00 UTC by jiyun-par

2022-12-26 04:45 UTC, isabellaji requested changes

2022-12-26 04:45 UTC, isabellaji commented on styles/signup.style.tsx
> +  h1 {
다른 태그의 스타일을 줄 때 한 줄 씩 띄어 쓸 것인지 붙여 쓸 것인지 일정하게 부탁드립니다~!

2022-12-26 04:45 UTC, isabellaji commented on pages/signup.tsx
> +        <h1>회원가입</h1>
h1태그는 페이지 로고에만 사용 부탁드립니다!

2022-12-26 04:45 UTC, isabellaji commented on pages/signup.tsx
> +      <header>
해당페이지에서는 header 태그 사용이 부적절해보입니다! 추후에 메인 페이지를 위한 공통 header 컴포넌트를 만들게 될 텐데 해당 컴포넌트에서 header태그를 사용할 것 같아요!

2022-12-26 04:45 UTC, isabellaji commented on pages/signup.tsx
> +import Image from 'next/image';
로그인 페이지 참고하셔서 import 순서 변경부탁드려요!

2022-12-26 04:45 UTC, isabellaji commented on pages/signup.tsx
> +          errorMsg={errors.displayName ? '' : errors.email?.message}
이 부분은 왜 displayName이 기준인지 설명 추가 부탁드립니다

2022-12-26 04:45 UTC, isabellaji commented on pages/signup.tsx
> +          errorMsg={errors.email ? '' : errors.password?.message}
이 부분은 왜 email이 기준인지 설명 추가 부탁드립니다

2022-12-26 06:33 UTC, jiyun-par commented on pages/signup.tsx
> +        <h1>회원가입</h1>
h1태그는 해당 페이지에 타이틀을 의미하는데 로고만 넣는 이유가 있을까용?

2022-12-27 01:01 UTC, isabellaji commented on pages/signup.tsx
> +        <h1>회원가입</h1>
header를 사용하는 이유랑 동일해요! 나중에 header 컴포넌트 따로 만들어서 관리하니깐용!

2022-12-27 01:08 UTC, isabellaji commented
가입하기 화면 하단 여백 좀 더 있으면 좋을 것 같습니다!

2022-12-27 01:23 UTC, isabellaji requested changes

2022-12-27 01:23 UTC, isabellaji commented on pages/signup.tsx
> +          type="email"
type에 email로 지정하면 에러메세지가 영어로 나와용!

2022-12-28 01:57 UTC, isabellaji approved these changes

2022-12-28 01:57 UTC, isabellaji commented
나중에 header 부분은 공통으로 쓰는 방법도 생각해보자구용~!

2022-12-28 14:21 UTC, sso-hyeon approved these changes

2022-12-30 01:49 UTC, merged