Feat: 회원가입 기능 구현
lulutraining/lulutraining pull request #38
Opened 2022-12-30 04:47 UTC by jiyun-par

[회원가입 기능 관련 내용]
1. 회원가입 에러 처리
- 회원가입 클릭시 이미 존재하는 이메일인 경우 AuthError로 하단에 메세지 노출
- 위 에러 발생시 email input focus
- email input error: signupError가 존재 할 경우 기타 error는 노출하지 않음

2. auth.ts
- signup: 회원가입 시
- updateProfile : user profile 추가

[component 관련 내용]
1. AuthError component 코드 수정 및 추가
- return이 있으므로 break문은 삭제
- 'auth/email-already-in-use' 추가

2. components/Header/signup: signup 상단 UI 컴포넌트로 분리
- title: 페이지 제목

4. Loader component
https://uiball.com/loaders/
- 위 라이브리러리 적용
- loaderText: 링 안에 텍스트를 넣을경우 추가

2023-01-01 14:29 UTC, sso-hyeon approved these changes

2023-01-02 01:57 UTC, isabellaji requested changes

2023-01-02 01:57 UTC, isabellaji commented on components/Header/signup/index.tsx
> +import { Container } from './style';
이렇게 가입하기만 단독으로 사용하기위해서 컴포넌트로 따로 빼는건 컴포넌트로 따로 뺄 이유가 없어욤
이부분은 다시 페이지로 넣어주세용! 컴포넌트로 뺄때는 재사용성을 고려 부탁드리고, 만약 컴포넌트 따로 빼는 작업하게 된다면 그건 다른 pr로 남겨주세요!

2023-01-02 02:22 UTC, jiyun-par commented on components/Header/signup/index.tsx
> +import { Container } from './style';
이 부분은 신체기입에서도 동일하게 사용되서 컴포넌트로 분리했는데 각각 넣는게 나을까요?

2023-01-02 02:36 UTC, isabellaji requested changes

2023-01-02 02:36 UTC, isabellaji commented on pages/signup.tsx
> +      await authAPI.signup({ email, password });
사용자 프로파일 저장 & 로그인 토큰 저장 추가해주세요~!

2023-01-02 02:36 UTC, isabellaji commented on components/Header/signup/index.tsx
> +import { Container } from './style';
그렇게 생각하면 로그인페이지에서도 메인페이지에서도 다 header를 동일하게 사용하는걸용

2023-01-02 06:15 UTC, isabellaji requested changes

2023-01-02 06:15 UTC, isabellaji commented on pages/signup.tsx
> +      await router.push('/signup/body-check');
여기는 비동기 빼주세용

2023-01-02 06:15 UTC, isabellaji commented on pages/signup.tsx
> +        user: getAuth().currentUser as User,
getAuth().currentUser 이부분은 authAPI.signup({ email, password })로 대체해주세요~!

2023-01-02 06:15 UTC, isabellaji commented on pages/signup.tsx
> +        displayName: displayName as string,
이부분은 auth type 정의한 RequestAuth에서 displayName을 옵션으로 지정하지 않고 displayName만 따로 빼서 상속하는 걸로 만들면 as string을 사용하지 않을 수 있어요! as는 도저히 코드를 고칠 수 없을때만 사용하기!

2023-01-02 07:29 UTC, jiyun-par commented on pages/signup.tsx
> +        user: getAuth().currentUser as User,
updateProfile은 현재 로그인된 현재 유저를 가져와야 하기 때문에, 해당 부분으로 대체는 안됩니다..!

2023-01-03 01:46 UTC, isabellaji requested changes

2023-01-03 01:46 UTC, isabellaji commented on pages/signup.tsx
> +      localStorage.setItem('oz-user-profile', JSON.stringify({ diplayName: user.displayName }));
displayName은 recoil에서 관리하고 있으니 localStorage에서 저장하는 작업은 상태관리하는 쪽에서 한꺼번에 하는 방향으로 바꿔주세용

2023-01-03 01:46 UTC, isabellaji commented on pages/signup.tsx
> +      setUserProfile({ displayName: user.displayName as string });
as string 빼주세욤! 저번에도 말했듯이 as는 코드를 도저히 고칠 수 없을때만 하는걸루~~

2023-01-03 06:17 UTC, isabellaji commented on pages/signup.tsx
> +      localStorage.setItem('oz-user-profile', JSON.stringify({ diplayName: user.displayName }));
이 부분 다시 확인 부탁드려요~

2023-01-06 01:34 UTC, isabellaji approved these changes

2023-01-06 03:40 UTC, merged