Feature/oz 25 active check
lulutraining/lulutraining pull request #43
Opened 2023-01-09 11:57 UTC by sso-hyeon

활동량 체크 UI 구현

2023-01-10 04:59 UTC, Jiyun-Parkk commented on consts/activeQuestions.ts
> +}
act는 active, ques는 question으로 명확한 단어로 쓰면 더 좋을 것 같아용!
그리고 actType은 다른데서 사용하지 않는 것 같은데 export 한 이유가 있을까요?

2023-01-10 04:59 UTC, jiyun-par commented on pages/activecheck.tsx
> +
이전 버튼을 클릭하면 다음 질문들에서 선택했던 답이 사라져용!
이전 버튼으로 전전 질문으로 이동하고 다시 다음을 눌렀을때에도 
다음 질문들에서 선택했던 답지가  모두 저장되어 있으면 좋을 것 같아욤

2023-01-13 01:01 UTC, isabellaji requested changes

2023-01-13 01:01 UTC, isabellaji commented on pages/activecheck.tsx
> +  console.log(1);
console.log 지워주세용

2023-01-13 01:01 UTC, isabellaji commented on pages/activecheck.tsx
> +  const handleChange = (event: React.MouseEvent<HTMLElement>, answerCount: number) => {
함수명은 handleChangeOOO으로 명확하게 변경해주세용

2023-01-13 01:08 UTC, isabellaji requested changes

2023-01-13 01:08 UTC, isabellaji commented on consts/activeQuestions.ts
> +export const activeQuestion: actType[] = [
이 부분은 firebase DB에 넣어서 사용해주세요~!

2023-01-17 11:46 UTC, sso-hyeon commented on consts/activeQuestions.ts
> +export const activeQuestion: actType[] = [
근데 혹시 왜 DB에 넣어서 가져와야 하는건가요?

2023-01-21 12:10 UTC, Jiyun-Parkk commented on apis/database.ts
> +import { firestore } from 'services/firebase';
사용하지 않는 모듈은 삭제 부탁드리겠습니당~!

2023-01-21 12:10 UTC, Jiyun-Parkk commented on pages/activecheck.tsx
> +          } catch (error) {
return false는 삭제해도 될 것 같습니당~!

2023-01-21 12:10 UTC, jiyun-par commented on pages/activecheck.tsx
> +interface actType {
type 명이 더 명확하면 좋을 것 같아용!
그리고 type 이름 첫글자는 대문자로 부탁드리겠습니다! :)

https://radlohead.gitbook.io/typescript-deep-dive/styleguide#%EC%9D%B8%ED%84%B0%ED%8E%98%EC%9D%B4%EC%8A%A4

2023-01-21 12:10 UTC, jiyun-par commented on pages/activecheck.tsx
> +interface answerList {
이 interface 이름도 마찬가지로 첫문자 대문자로 부탁드립니당!

2023-01-21 14:55 UTC, jiyun-par approved these changes

2023-01-26 15:35 UTC, isabellaji approved these changes

2023-01-29 12:57 UTC, merged