Feat: 신체정보 기입 , 활동량 체크 하기 전 기업 여부 체크 페이지 UI 구현
lulutraining/lulutraining pull request #46
Opened 2023-01-13 01:36 UTC by jiyun-par

1. router query값에 따라 메인 텍스트 렌더링
 - signup/body-check : 신체정보 기입 여부 체크
 - signup/active-check: 활동량 기업 여부 체크

2. 활동량 기입 여부 체크 페이지에서 건너띄기 => 스플래쉬 => 메인 이동

3. getServerSideProps
sign/[check].js가 body-check , active-check에서만 접근가능 하도록
이외의 값은 404 page 노출

2023-01-21 02:05 UTC, isabellaji requested changes

2023-01-21 02:05 UTC, isabellaji commented on pages/signup/[check].tsx
>  const CheckNext = () => {
컴포넌트명은 좀더 정확하게 변경하면 좋을 것 같아요!

2023-01-21 02:05 UTC, isabellaji commented on pages/signup/[check].tsx
> +  useEffect(() => {
텍스트 넣는 부분과 isComplete 모두 useEffect내에서 사용하지 않는 것이 좋을 것 같아요!
페이지에 텍스트를 넣는 부분은 내용이 짧으니 반복문보단 그대로 작성하면 좋겠어요!

2023-01-25 01:10 UTC, isabellaji approved these changes

2023-01-25 01:17 UTC, sso-hyeon approved these changes

2023-01-25 02:11 UTC, merged