Feat: 로그인 없이 서비스 페이지 진입시 노출될 모달 컴포넌트 구현
lulutraining/lulutraining pull request #49
Opened 2023-01-17 10:35 UTC by jiyun-par

- 신체정보 기입 / 활동량 체크 / 메인 페이지 / 마이페이지 / 콘텐츠 시청 페이지 등
- 로그인이 필요한 서비스 페이지에서는 로그인 유무 체크하여 모달 노출
- 로그인 버튼 => 로그인 화면

2023-01-21 02:12 UTC, isabellaji requested changes

2023-01-21 02:12 UTC, isabellaji commented on components/Modal/index.tsx
> +export const LoginModal = () => {
UnauthorizedResult는 어떠신가요? 해당 컴포넌트의 역할을 더 명확하게 해주는게 좋을 것 같아요!

2023-01-21 02:12 UTC, isabellaji commented on components/Modal/index.tsx
> +  const [isLogin, setIsLogin] = useState(true);
이 부분은 이 컴포넌트를 사용하는 곳에서 처리해야할 부분인 것 같아용
해당 컴포너트는 UI만 보여주면 될 것 같습니다~!

2023-01-25 01:12 UTC, isabellaji approved these changes

2023-01-25 01:17 UTC, sso-hyeon approved these changes

2023-01-25 02:11 UTC, merged