Feat: Layout 컴포넌트에 Modal 컴포넌트 추가
lulutraining/lulutraining pull request #51
Opened 2023-01-25 07:19 UTC by jiyun-par

- 회원가입 / 로그인 페이지 제외한 모든 페이지에서 로그인이 안되었을시 모달 컴포넌트 노출

2023-01-25 13:20 UTC, sso-hyeon approved these changes

2023-01-25 14:08 UTC, isabellaji requested changes

2023-01-25 14:08 UTC, isabellaji commented on components/Modal/index.tsx
파일명도 UnathorizedResult로 변경부탁드려요!

2023-01-26 15:36 UTC, isabellaji approved these changes

2023-01-26 16:16 UTC, merged