Feat: 운동량 체크 디자인 변경 및 기능 구현
lulutraining/lulutraining pull request #60
Opened 2023-02-08 15:45 UTC by sso-hyeon

2023-02-09 08:50 UTC, jiyun-par commented on styles/activeCheck.style.tsx
> +export const Container: React.ElementType = styled.div`
요기 타입은 왜 들어간건가용?

2023-02-12 15:28 UTC, jiyun-par approved these changes

2023-02-13 01:19 UTC, isabellaji requested changes

2023-02-13 01:19 UTC, isabellaji commented on pages/activecheck.tsx
> -import { PrevNextButton } from 'components';
제일 처음 페이지 진입시 progress bar가 1에서 시작에서 0으로 가는 오류가 있어요!

2023-02-13 01:21 UTC, isabellaji requested changes

2023-02-13 01:21 UTC, isabellaji commented on pages/activecheck.tsx
> +            <CustomButton variant="contained" type="button" onClick={() => router.push('/')}>
함수는 따로 만들어주세요

2023-02-13 01:21 UTC, isabellaji commented on pages/activecheck.tsx
> +          <>
해당 부분은 결과창으로 따로 컴포넌트로 빼는게 좋을 것 같습니다

2023-02-13 01:23 UTC, isabellaji requested changes

2023-02-13 01:23 UTC, isabellaji commented on pages/activecheck.tsx
>    useEffect(() => {
해당 부분은 클릭함수에서 처리하지 않고 useEffect에서 하는 이유가 있을까요?

2023-02-13 01:25 UTC, isabellaji requested changes

2023-02-13 01:25 UTC, isabellaji commented on pages/activecheck.tsx
> +              return (
return 빼주실 수 있나용?

2023-02-13 01:25 UTC, isabellaji commented on pages/activecheck.tsx
> +                    onChange={(event, answerCount: number) =>
이미 해당 함수에서 type을 적어줬으니 여기선 빼주도록해용

2023-02-19 15:40 UTC, sso-hyeon commented on pages/activecheck.tsx
>    useEffect(() => {
해당 부분은 동기적으로 처리되어야 작동이 되는 것 같아 useEffect 사용하여 처리했습니다! 다른 방법이 있는 건가요?

2023-02-21 00:25 UTC, isabellaji requested changes

2023-02-21 00:25 UTC, isabellaji commented on pages/activecheck.tsx
>    useEffect(() => {
소현님 생각은 다른 방법이 없어서 이걸 사용했다는 건가요?

2023-02-21 00:30 UTC, isabellaji commented
@sso-hyeon 소현님 pr master pull 받아주세요

2023-02-21 00:31 UTC, isabellaji requested changes

2023-02-21 00:31 UTC, isabellaji commented on components/ActivecheckResult/index.tsx
> +import { Container, CustomButton } from './style';
소현님 pr master pull 받아주세요

2023-02-21 00:47 UTC, isabellaji approved these changes

2023-02-21 04:36 UTC, sso-hyeon commented on pages/activecheck.tsx
>    useEffect(() => {
넹넹! 다른 방법을 찾지 못해 useEffect 사용했습니다!

2023-02-21 04:37 UTC, sso-hyeon commented on components/ActivecheckResult/index.tsx
> +import { Container, CustomButton } from './style';
master pull 받고 진행한건데 혹시 어디 문제가 있는걸까요..?

2023-02-22 01:15 UTC, isabellaji commented on components/ActivecheckResult/index.tsx
> +import { Container, CustomButton } from './style';
제가 소현님꺼 pr 받았을때는 컨플릭이 나서 그랬어요! 문제 없다면 머지하셔도 될 것 같아요!

2023-02-22 02:30 UTC, merged