Feat: unAuthorizedCheck, removeCookie 유틸 함수 구현
lulutraining/lulutraining pull request #64
Opened 2023-02-22 07:17 UTC by jiyun-par

### unAuthorizedCheck.ts
getServerSideProps 함수에서 사용할 유저 인증 체크 함수

✅ unAuthorizedCheck 파라미터

```javascript
  user: 쿠키에 담긴 user의 토큰
  context: GetServerSidePropsContext;
  propsOption?: props로 보내줄 데이터
```

props 데이터를 unAuthorizedCheck 내부에서 처리해주는 이유는
geServerSideProps 에서 unAuthorizedCheck를 return으로 처리해주어야 동작하기때문입니다.

#### 구현

1. user 쿠키가 존재하는 경우
  - `verifySessionCookie()`로 유저의 유효성 체크
  - 유효한 경우: 회원가입이나 로그인 페이지면 메인페이지로 리다이렉트
  - 유효하지 않는 경우: 저장되어있던 쿠키 삭제
    - 신체기입이나 활동량체크와 같이 로그인이 꼭 필요한 서비스 페이지에서는 로그인 페이지로 리다이렉트
  
 2.  user 쿠키가 존재하지 않는 경우
 - 신체기입이나 활동량체크와 같이 로그인이 꼭 필요한 서비스 페이지에서는 로그인 페이지로 리다이렉트
 
### removeCookie.ts
cookie 삭제하는 유틸 함수
unAuthorizedCheck.ts, api/auth/logout.ts 에서 사용하여 유틸함수로 분리했습니다.

2023-02-22 12:31 UTC, sso-hyeon approved these changes

2023-02-24 00:48 UTC, isabellaji requested changes

2023-02-24 00:48 UTC, isabellaji commented on utils/unAuthorizedCheck.ts
> +  const verifyUser = async (user: string) => {
요 부분 함수로 안 묶고 try catch할때 amdinAuth.verifySessionCookie()로 바로 처리해줘도 될 것 같아용!

2023-02-26 01:06 UTC, isabellaji approved these changes

2023-02-26 01:27 UTC, merged